[package]
name = "auth"
version = "0.0.1"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Sylva Hearth auth module"

[lib]
name = "auth"
path = "src/lib.rs"

[dependencies]
identity = { path = "../identity" }

argon2 = { workspace = true }
sha2 = { workspace = true }
sha1 = { workspace = true }
hmac = { workspace = true }
subtle = { workspace = true }
base32 = { workspace = true }
chacha20poly1305 = { workspace = true }
rand = { workspace = true }

sqlx = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true
