[package]
name = "web"
version = "0.0.1"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Sylva Hearth web UI"

[lib]
path = "src/lib.rs"

[dependencies]
axum = { workspace = true }
tower-http = { workspace = true, features = ["fs", "trace"] }
tracing = { workspace = true }
uuid = { workspace = true }
maud = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }

hearth = { path = "../hearth" }
identity = { path = "../identity" }
auth = { path = "../auth" }
audit = { path = "../audit" }

[lints]
workspace = true
